language: csharp
solution: ./HTTPServer/HTTPServer.sln
mono: 
  - latest

notifications:
  email:
    recipients:
      - 875974254@qq.com
      - qinyuanpei@163.com
    on_success: change # default: change
    on_failure: always # default: always

install:
  - nuget restore ./HTTPServer/HTTPServer.sln
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory TestRunner

script:
  - cd ./HTTPServer
  - xbuild /p:Configuration=Release HTTPServer.sln
  - mono ./testrunner/NUnit.Runners.3.8.0/tools/nunit-console.exe ./HTTPServerLib.UnitTest/bin/Release/HTTPServerLib.UnitTest.dll

branches:
  only:
    - master

